### PR TITLE
Medals by age graph

### PR DESCRIPTION
**Pull request by AndyYang80**
Added matrix structure to app.py and athlete age histogram, moved former app.py to app_scatter_hist.py

### CODE REVIEW

**Comment by ruben1dlg** [comment]
I just took a look and it looks pretty nice! I just noticed that the year slider is in the bottom for the layout, and I think it should be on the top, since it is affecting all the graphs! 😀

**Comment by AndyYang80** [comment]
Currently, the year slider is only affecting the two graphs on the left (bubble chart and ahtlete height) so I left it on the bottom left

**Comment by ruben1dlg** [comment]
Ooh okok, great! I thought it was affecting the other plots as well! Looks very good!!

**Comment by helingogo** [comment]
Fantastic work！I think if we have extra time, we can color the title  or color the background of the title; Also for each chart, we can applied card to make it looks more organized and aligned, like this:

image

**Comment by AndyYang80** [comment]
I can look into the suggested changes, I'll see if I have time to implement them by tomorrows meeting

**Pull request merged**
